
# apiVersion: v1
# kind: Pod
# metadata:
#   name: phuongtd-app
# spec:
#   containers:
#   - name: phuongtd-app
#     image: 798426491631.dkr.ecr.ap-southeast-1.amazonaws.com/ecr_phuongtd:latest
#     ports:
#     - containerPort: 80
#   imagePullSecrets:
#   - name: phuongtd-secret-ecr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phuongtd-app
  name: phuongtd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phuongtd-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: phuongtd-app
    spec:
      containers:
      - image: NONEXIST
        name: phuongtd-app
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: phuongtd-secret-ecr