# apiVersion: v1
# kind: Service
# metadata:
#   name: phuongtd-svc
# spec:
#   selector:
#     app: phuongtd-app
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#       name: http
---
apiVersion: v1
kind: Service
metadata:
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: phuongtd-svc
  name: phuongtd-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phuongtd-app
  type: LoadBalancer